//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLC_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class gasolina
    {
        public int Id { get; set; }
        public int Tag { get; set; }
        public string Litros { get; set; }
        public double Densidad { get; set; }
        public double Temperatura { get; set; }
        public double Flujo { get; set; }
        public string Totalizado { get; set; }
        public string Fecha_de__inicio { get; set; }
        public string Fecha_de_terminio { get; set; }
    }
}
