//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PLC_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class inicio
    {
        public int di { get; set; }
        public string inicio1 { get; set; }
        public Nullable<int> apagado { get; set; }
    }
}
